image: nixos/unstable
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
sources:
- https://git.sr.ht/~fgaz/bachelor-thesis
secrets:
- cdcf0901-9843-4671-9d5f-aaf61b86da53
tasks:
- build: |
    cd bachelor-thesis
    nix-build
- publish: |
    cd bachelor-thesis
    t=$(date -uIseconds)
    c=$(git rev-parse HEAD)
    curl -T result/Gazzetta_Francesco_Informatica_19.pdf -ufgaz https://api.bintray.com/content/fgaz/bachelor-thesis/thesis-unstable/unstable-$t-$c/Gazzetta_Francesco_Informatica_19_unstable-$t-$c.pdf?publish=1 < ~/.bintray-api-key

