image: nixos/unstable
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
sources:
- https://git.sr.ht/~fgaz/bachelor-thesis
secrets:
- 49b46368-137e-441f-bf8c-cf9a7a7e9a7d
tasks:
- build: |
    cd bachelor-thesis
    nix-build
- publish: |
    cd bachelor-thesis
    t=$(date -uIseconds)
    c=$(git rev-parse HEAD)
    curl --netrc-file ~/.bintray-api-key.netrc -T result/Gazzetta_Francesco_Informatica_19.pdf https://api.bintray.com/content/fgaz/bachelor-thesis/thesis-unstable/unstable-$t-$c/Gazzetta_Francesco_Informatica_19_unstable-$t-$c.pdf?publish=1

